//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPlanner.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Destination { get; set; }
        public string Comment { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
